### ISSUE TITLE
MarshalToString Panic

### ISSUE THREAD

**Issue by yumaojun03** [json-iterator/go#16]
golang 1.8  

code 

```golang
package main

import json "github.com/json-iterator/go"
import "fmt"

type Test struct {
	Name string              `json:"name"`
	Data []map[string]string `json:"data"`
}

func main() {
	sub := make(map[string]string)
	sub["key"] = "value"

	t := Test{Name: "test", Data: []map[string]string{sub}}
	jsonStr, _ := json.MarshalToString(t)
	fmt.Println(jsonStr)
```

panic

```golang
unexpected fault address 0xb01dfacedebac1e
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x8c34]

goroutine 1 [running]:
runtime.throw(0xe40ab, 0x5)
	/usr/local/Cellar/go/1.7.4/libexec/src/runtime/panic.go:566 +0x95 fp=0xc42003b8b0 sp=0xc42003b890
runtime.sigpanic()
	/usr/local/Cellar/go/1.7.4/libexec/src/runtime/sigpanic_unix.go:27 +0x288 fp=0xc42003b908 sp=0xc42003b8b0
runtime.mapiternext(0xc42006a060)
	/usr/local/Cellar/go/1.7.4/libexec/src/runtime/hashmap.go:731 +0xe4 fp=0xc42003b9b0 sp=0xc42003b908
runtime.mapiterinit(0xc7740, 0xc420028030, 0xc42006a060)
	/usr/local/Cellar/go/1.7.4/libexec/src/runtime/hashmap.go:679 +0x1c1 fp=0xc42003b9f0 sp=0xc42003b9b0
reflect.mapiterinit(0xc7740, 0xc420028030, 0x15)
	/usr/local/Cellar/go/1.7.4/libexec/src/runtime/hashmap.go:1029 +0x54 fp=0xc42003ba20 sp=0xc42003b9f0
reflect.Value.MapKeys(0xc7740, 0xc420028030, 0x15, 0xc420028030, 0x15, 0x0)
	/usr/local/Cellar/go/1.7.4/libexec/src/reflect/value.go:1074 +0xc0 fp=0xc42003bac8 sp=0xc42003ba20
github.com/json-iterator/go.(*mapEncoder).encode(0xc42000e280, 0xc420028030, 0xc420010140)
	/Users/maojun/GoWorkDir/src/github.com/json-iterator/go/feature_reflect.go:241 +0xba fp=0xc42003bb78 sp=0xc42003bac8
github.com/json-iterator/go.(*sliceEncoder).encode(0xc4200164e0, 0xc420016400, 0xc420010140)
	/Users/maojun/GoWorkDir/src/github.com/json-iterator/go/feature_reflect_array.go:40 +0x89 fp=0xc42003bc00 sp=0xc42003bb78
github.com/json-iterator/go.(*structFieldEncoder).encode(0xc420016510, 0xc4200163f0, 0xc420010140)
	/Users/maojun/GoWorkDir/src/github.com/json-iterator/go/feature_reflect_object.go:1037 +0x97 fp=0xc42003bc80 sp=0xc42003bc00
github.com/json-iterator/go.(*structEncoder).encode(0xc4200122e0, 0xc4200163f0, 0xc420010140)
	/Users/maojun/GoWorkDir/src/github.com/json-iterator/go/feature_reflect_object.go:1067 +0x94 fp=0xc42003bcd0 sp=0xc42003bc80
github.com/json-iterator/go.WriteToStream(0xcc8a0, 0xc4200163f0, 0xc420010140, 0x15ac80, 0xc4200122e0)
	/Users/maojun/GoWorkDir/src/github.com/json-iterator/go/feature_reflect.go:35 +0xfa fp=0xc42003bd10 sp=0xc42003bcd0
github.com/json-iterator/go.(*structEncoder).encodeInterface(0xc4200122e0, 0xcc8a0, 0xc4200163f0, 0xc420010140)
	/Users/maojun/GoWorkDir/src/github.com/json-iterator/go/feature_reflect_object.go:1074 +0x55 fp=0xc42003bd48 sp=0xc42003bd10
github.com/json-iterator/go.(*Stream).WriteVal(0xc420010140, 0xcc8a0, 0xc4200163f0)
	/Users/maojun/GoWorkDir/src/github.com/json-iterator/go/feature_reflect.go:344 +0xa8 fp=0xc42003bdb8 sp=0xc42003bd48
github.com/json-iterator/go.Marshal(0xcc8a0, 0xc4200163f0, 0xc42003be58, 0xc49b, 0xcc8a0, 0xc4200163f0, 0xc42003bf10)
	/Users/maojun/GoWorkDir/src/github.com/json-iterator/go/feature_adapter.go:74 +0x144 fp=0xc42003be20 sp=0xc42003bdb8
github.com/json-iterator/go.MarshalToString(0xcc8a0, 0xc4200163f0, 0xc4200163f0, 0xcc8a0, 0xc4200163f0, 0x1)
	/Users/maojun/GoWorkDir/src/github.com/json-iterator/go/feature_adapter.go:83 +0x39 fp=0xc42003be68 sp=0xc42003be20
main.main()
	/Users/maojun/GoWorkDir/src/test.go:16 +0x1d1 fp=0xc42003bf48 sp=0xc42003be68
runtime.main()
	/usr/local/Cellar/go/1.7.4/libexec/src/runtime/proc.go:183 +0x1f4 fp=0xc42003bfa0 sp=0xc42003bf48
runtime.goexit()
	/usr/local/Cellar/go/1.7.4/libexec/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc42003bfa8 sp=0xc42003bfa0
exit status 2
```

**Comment by yumaojun03** [comment]
将map[string]string 换成  interface{}  就ok，但是不知道为啥 指明类型反而不行

**Comment by taowen** [comment]
应该是有些问题，我查一下

**Comment by taowen** [comment]
fixed

**Comment by yumaojun03** [comment]
Thanks.
