### ISSUE TITLE
fatal error: runtime: name offset base pointer out of range

### ISSUE THREAD

**Issue by taowen** [json-iterator/go#197]
```
runtime: nameOff 0xc422ba base 0xc422ba59fa not in ranges:
  types 0x8ac000 etypes 0xa2f130
fatal error: runtime: name offset base pointer out of range

goroutine 115 [running]:
runtime.throw(0x9ccc92, 0x2e)
  /usr/lib/golang/src/runtime/panic.go:566 +0x95 fp=0xc42348cf08 sp=0xc42348cee8
runtime.resolveNameOff(0xc422ba59fa, 0x7f5200c422ba, 0x1)
  /usr/lib/golang/src/runtime/type.go:193 +0x221 fp=0xc42348cf70 sp=0xc42348cf08
reflect.resolveNameOff(0xc422ba59fa, 0x7f5200c422ba, 0xc42348cfd8)
  /usr/lib/golang/src/runtime/runtime1.go:493 +0x33 fp=0xc42348cf98 sp=0xc42348cf70
reflect.(*rtype).nameOff(0xc422ba59fa, 0x7f5200c422ba, 0x19)
  /usr/lib/golang/src/reflect/type.go:663 +0x33 fp=0xc42348cfc0 sp=0xc42348cf98
reflect.(*rtype).String(0xc422ba59fa, 0x71c2ab, 0x7b431f)
  /usr/lib/golang/src/reflect/type.go:733 +0x36 fp=0xc42348d000 sp=0xc42348cfc0
go.intra.xiaojukeji.com/pt-arch/DHSE/vendor/github.com/json-iterator/go._getTypeEncoderFromExtension(0xc49800, 0xc422ba59fa, 0xc42348d0b8, 0x71c00c)
  /root/DHSE/build/src/go.intra.xiaojukeji.com/pt-arch/DHSE/vendor/github.com/json-iterator/go/feature_reflect_extension.go:211 +0xba fp=0xc42348d068 sp=0xc42348d000
go.intra.xiaojukeji.com/pt-arch/DHSE/vendor/github.com/json-iterator/go.getTypeEncoderFromExtension(0xc49800, 0xc422ba59fa, 0xc422ba59fa, 0x0)
  /root/DHSE/build/src/go.intra.xiaojukeji.com/pt-arch/DHSE/vendor/github.com/json-iterator/go/feature_reflect_extension.go:195 +0x39 fp=0xc42348d0c8 sp=0xc42348d068
go.intra.xiaojukeji.com/pt-arch/DHSE/vendor/github.com/json-iterator/go.encoderOfType(0xc4200c0480, 0xc49800, 0xc422ba59fa, 0xc49800, 0x917d60, 0xc42540, 0xc843c8)
  /root/DHSE/build/src/go.intra.xiaojukeji.com/pt-arch/DHSE/vendor/github.com/json-iterator/go/feature_reflect.go:444 +0x80 fp=0xc42348d150 sp=0xc42348d0c8
go.intra.xiaojukeji.com/pt-arch/DHSE/vendor/github.com/json-iterator/go.(*Stream).WriteVal(0xc4200a65a0, 0xc422ba59fa, 0x5)
  /root/DHSE/build/src/go.intra.xiaojukeji.com/pt-arch/DHSE/vendor/github.com/json-iterator/go/feature_reflect.go:247 +0x6e fp=0xc42348d1a8 sp=0xc42348d150
go.intra.xiaojukeji.com/pt-arch/DHSE/vendor/github.com/json-iterator/go.(*emptyInterfaceCodec).Encode(0xc843c8, 0xc422ba5a80, 0xc4200a65a0)
  /root/DHSE/build/src/go.intra.xiaojukeji.com/pt-arch/DHSE/vendor/github.com/json-iterator/go/feature_reflect_native.go:369 +0x41 fp=0xc42348d1d0 sp=0xc42348d1a8
go.intra.xiaojukeji.com/pt-arch/DHSE/vendor/github.com/json-iterator/go.(*placeholderEncoder).Encode(0xc42359e300, 0xc422ba5a80, 0xc4200a65a0)
  /root/DHSE/build/src/go.intra.xiaojukeji.com/pt-arch/DHSE/vendor/github.com/json-iterator/go/feature_reflect.go:163 +0x53 fp=0xc42348d1f8 sp=0xc42348d1d0
go.intra.xiaojukeji.com/pt-arch/DHSE/vendor/github.com/json-iterator/go.WriteToStream(0x8fc000, 0xc422ba5a80, 0xc4200a65a0, 0xc42a80, 0xc42359e300)
  /root/DHSE/build/src/go.intra.xiaojukeji.com/pt-arch/DHSE/vendor/github.com/json-iterator/go/feature_reflect.go:49 +0x107 fp=0xc42348d238 sp=0xc42348d1f8
go.intra.xiaojukeji.com/pt-arch/DHSE/vendor/github.com/json-iterator/go.(*placeholderEncoder).EncodeInterface(0xc42359e300, 0x8fc000, 0xc422ba5a80, 0xc4200a65a0)
  /root/DHSE/build/src/go.intra.xiaojukeji.com/pt-arch/DHSE/vendor/github.com/json-iterator/go/feature_reflect.go:167 +0x55 fp=0xc42348d270 sp=0xc42348d238
go.intra.xiaojukeji.com/pt-arch/DHSE/vendor/github.com/json-iterator/go.(*sortKeysMapEncoder).Encode(0xc422426200, 0xc423202660, 0xc4200a65a0)
  /root/DHSE/build/src/go.intra.xiaojukeji.com/pt-arch/DHSE/vendor/github.com/json-iterator/go/feature_reflect_map.go:195 +0x48e fp=0xc42348d3b8 sp=0xc42348d270
go.intra.xiaojukeji.com/pt-arch/DHSE/vendor/github.com/json-iterator/go.WriteToStream(0x925280, 0xc423202660, 0xc4200a65a0, 0xc42b00, 0xc422426200)
  /root/DHSE/build/src/go.intra.xiaojukeji.com/pt-arch/DHSE/vendor/github.com/json-iterator/go/feature_reflect.go:49 +0x107 fp=0xc42348d3f8 sp=0xc42348d3b8
go.intra.xiaojukeji.com/pt-arch/DHSE/vendor/github.com/json-iterator/go.(*sortKeysMapEncoder).EncodeInterface(0xc422426200, 0x925280, 0xc423202660, 0xc4200a65a0)
  /root/DHSE/build/src/go.intra.xiaojukeji.com/pt-arch/DHSE/vendor/github.com/json-iterator/go/feature_reflect_map.go:235 +0x55 fp=0xc42348d430 sp=0xc42348d3f8
go.intra.xiaojukeji.com/pt-arch/DHSE/vendor/github.com/json-iterator/go.(*Stream).WriteVal(0xc4200a65a0, 0x925280, 0xc423202660)
  /root/DHSE/build/src/go.intra.xiaojukeji.com/pt-arch/DHSE/vendor/github.com/json-iterator/go/feature_reflect.go:252 +0xe9 fp=0xc42348d488 sp=0xc42348d430
go.intra.xiaojukeji.com/pt-arch/DHSE/vendor/github.com/json-iterator/go.(*frozenConfig).Marshal(0xc4200c0480, 0x925280, 0xc423202660, 0x0, 0x0, 0x0, 0x0, 0x0)
  /root/DHSE/build/src/go.intra.xiaojukeji.com/pt-arch/DHSE/vendor/github.com/json-iterator/go/feature_config.go:262 +0xdb fp=0xc42348d4f8 sp=0xc42348d488
```

**Comment by Zh3Wang** [comment]
Is this issue solved?
