### ISSUE TITLE
crash 

### ISSUE THREAD

**Issue by ruandao** [json-iterator/go#233]
```

unexpected fault address 0x0
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x558264]

goroutine 154345059 [running]:
runtime.throw(0x9dcad3, 0x5)
        /usr/local/go/src/runtime/panic.go:605 +0x95 fp=0xc42864f6c0 sp=0xc42864f6a0 pc=0x42d235
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:374 +0x227 fp=0xc42864f710 sp=0xc42864f6c0 pc=0x443d77
github.com/json-iterator/go.(*Stream).WriteStringWithHTMLEscaped(0xc421e11260, 0x2e30313a746f6873, 0x303030303030)
        /root/fishSer/src/github.com/json-iterator/go/feature_stream_string.go:235 +0x94 fp=0xc42864f748 sp=0xc42864f710 pc=0x558264
github.com/json-iterator/go.(*htmlEscapedStringEncoder).Encode(0xce5f68, 0xc421bae000, 0xc421e11260)
        /root/fishSer/src/github.com/json-iterator/go/feature_config.go:186 +0x41 fp=0xc42864f770 sp=0xc42864f748 pc=0x52f2a1
github.com/json-iterator/go.(*sliceEncoder).Encode(0xc421906870, 0xc42cc4e010, 0xc421e11260)
        /root/fishSer/src/github.com/json-iterator/go/feature_reflect_slice.go:45 +0x11f fp=0xc42864f800 sp=0xc42864f770 pc=0x54c48f
github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc42195f440, 0xc42cc4e000, 0xc421e11260)
        /root/fishSer/src/github.com/json-iterator/go/feature_reflect_object.go:113 +0x5c fp=0xc42864f880 sp=0xc42864f800 pc=0x54ad9c
github.com/json-iterator/go.(*structEncoder).Encode(0xc42195d200, 0xc42cc4e000, 0xc421e11260)
        /root/fishSer/src/github.com/json-iterator/go/feature_reflect_object.go:151 +0xfb fp=0xc42864f938 sp=0xc42864f880 pc=0x54b0fb
github.com/json-iterator/go.(*OptionalEncoder).Encode(0xc4213093e0, 0xc428817618, 0xc421e11260)
        /root/fishSer/src/github.com/json-iterator/go/feature_reflect_optional.go:73 +0x4f fp=0xc42864f960 sp=0xc42864f938 pc=0x54bb5f
github.com/json-iterator/go.WriteToStream(0x9c9000, 0xc42cc4e000, 0xc421e11260, 0xc87760, 0xc4213093e0)
        /root/fishSer/src/github.com/json-iterator/go/feature_reflect.go:47 +0xd2 fp=0xc42864f9a8 sp=0xc42864f960 pc=0x53a212
github.com/json-iterator/go.(*OptionalEncoder).EncodeInterface(0xc4213093e0, 0x9c9000, 0xc42cc4e000, 0xc421e11260)
        /root/fishSer/src/github.com/json-iterator/go/feature_reflect_optional.go:78 +0x55 fp=0xc42864f9e0 sp=0xc42864f9a8 pc=0x54bbd5
github.com/json-iterator/go.(*Stream).WriteVal(0xc421e11260, 0x9c9000, 0xc42cc4e000)
        /root/fishSer/src/github.com/json-iterator/go/feature_reflect.go:97 +0xae fp=0xc42864fa38 sp=0xc42864f9e0 pc=0x53a93e
github.com/json-iterator/go.(*frozenConfig).Marshal(0xc420078280, 0x9c9000, 0xc42cc4e000, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/fishSer/src/github.com/json-iterator/go/feature_config.go:266 +0xd6 fp=0xc42864faa8 sp=0xc42864fa38 pc=0x52fbc6
main/model/game.(*GameRoleAccount).Sync(0xc42cc4e000, 0xc4298bee60, 0x20, 0xc420162200, 0x3, 0xc4271c9f40)
        /root/fishSer/src/main/model/game/GameRoleAccount.go:96 +0x63 fp=0xc42864fbb8 sp=0xc42864faa8 pc=0x7ad1e3
main.(*Client).syncRoleAccount(0xc42221fc00, 0x0, 0x0)
        /root/fishSer/src/main/client.go:500 +0x3ab fp=0xc42864fd40 sp=0xc42864fbb8 pc=0x86e9fb
main.(*Client).writePump(0xc42221fc00)
        /root/fishSer/src/main/client.go:815 +0x406 fp=0xc42864ffd8 sp=0xc42864fd40 pc=0x872f56
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc42864ffe0 sp=0xc42864ffd8 pc=0x45e131
created by main.NewClient
        /root/fishSer/src/main/client.go:246 +0xd90

```

**Comment by taowen** [comment]
please provide an example input to reproduce the problem

**Comment by taowen** [comment]
there is no way to fix bug report like this.
