### ISSUE TITLE
Panic on Empty Array in Struct

### ISSUE THREAD

**Issue by dataBaseError** [json-iterator/go#239]
When parsing a payload with an empty array `json-iterator/go` will crash with a panic:
```
panic: Type.Set argument 1: expect *[]struct { TransactionID int "json:\"transactionId\""; TransactionTime int64 "json:\"transactionTime\""; Price float64 "json:\"price\""; Quantity float64 "json:\"quantity\"" }, actual unsafe.Pointer

goroutine 1 [running]:
github.com/v2pro/plz/reflect2.assertType(0x5a507e, 0x13, 0xc420024140, 0x562d80)
	/home/go/go/src/github.com/v2pro/plz/reflect2/unsafe_type.go:83 +0x1ff
github.com/v2pro/plz/reflect2.(*UnsafeSliceType).Set(0xc4200241c0, 0x562d80, 0xc42000a2c0, 0x562d80, 0xc42000a780)
	/home/go/go/src/github.com/v2pro/plz/reflect2/unsafe_slice.go:34 +0x66
github.com/json-iterator/go.(*sliceDecoder).doDecode(0xc42000a4a0, 0xc42000a2c0, 0xc4200cc300)
	/home/go/go/src/github.com/json-iterator/go/reflect_slice.go:81 +0x256
github.com/json-iterator/go.(*sliceDecoder).Decode(0xc42000a4a0, 0xc42000a2c0, 0xc4200cc300)
	/home/go/go/src/github.com/json-iterator/go/reflect_slice.go:61 +0x4c
github.com/json-iterator/go.(*structFieldDecoder).Decode(0xc42000a700, 0xc42000a2c0, 0xc4200cc300)
	/home/go/go/src/github.com/json-iterator/go/reflect_struct_decoder.go:970 +0x5c
github.com/json-iterator/go.(*oneFieldStructDecoder).Decode(0xc42000a760, 0xc42000a2c0, 0xc4200cc300)
	/home/go/go/src/github.com/json-iterator/go/reflect_struct_decoder.go:536 +0x91
github.com/json-iterator/go.(*Iterator).ReadVal(0xc4200cc300, 0x55b260, 0xc42000a2c0)
	/home/go/go/src/github.com/json-iterator/go/reflect.go:67 +0xae
github.com/json-iterator/go.(*frozenConfig).Unmarshal(0xc4200ce0c0, 0xc420018300, 0x35, 0x40, 0x55b260, 0xc42000a2c0, 0x0, 0x0)
	/home/go/go/src/github.com/json-iterator/go/config.go:275 +0x185
main.main()
	/home/go/go/src/test/test.go:21 +0xd0
exit status 2
```
So far I've only see this occur when the a target struct contains an array and the data payload for that array is empty. As per the example below the struct is defined with an array for `transactions` which in the payload data is empty: `{"transactions":[],"responseStatus":{"message":"OK"}}`. When the payload array contains entries it will work as expected. An example of a valid working payload would be:
```
{"transactions":[{"transactionId":64293019,"transactionTime":"1519138641","price":0.0001,"quantity":4.6}],"responseStatus":{"message":"OK"}}
```

Minimal example to reproduce the error:
```go
package main

import (
	"fmt"
	"github.com/json-iterator/go"
)

type response struct {
	Transactions []struct {
		TransactionID   int     `json:"transactionId"`
		TransactionTime string  `json:"transactionTime"`
		Price           float64 `json:"price"`
		Quantity        float64 `json:"quantity"`
	} `json:"transactions"`
}

func main() {
	byteData := []byte(`{"transactions":[],"responseStatus":{"message":"OK"}}`)
	var responseData response
	var json = jsoniter.ConfigCompatibleWithStandardLibrary
	if err := json.Unmarshal(byteData, &responseData); err != nil {
		fmt.Println(err)
	} else {
		fmt.Println("Works ", responseData)
	}
}
```

**Comment by dataBaseError** [comment]
@taowen right, sorry I didn't realise I was using 1.1
Thanks for your help.
