### ISSUE TITLE
panic but only during debug

### ISSUE THREAD

**Issue by sudo-suhas** [json-iterator/go#249]
I have this helper function for unmarshalling a string into a value:
```go
package jsonutil

import (
	"unsafe"

	jsoniter "github.com/json-iterator/go"
	"github.com/pkg/errors"
	log "github.com/sirupsen/logrus"
)

var (
	// def is the default config used for [un]marshalling values.
	// jsoniter.ConfigFastest marshals the float with 6 digits precision (lossy),
	// which is significantly faster. It also does not escape HTML.
	def = jsoniter.ConfigFastest
)

// Unmarshal uses jsoniter for efficiently unmarshalling the byte stream into
// the struct pointer.
func Unmarshal(data []byte, v interface{}) error { return UnmarshalWith(def, data, v) }

// UnmarshalWith uses the jsoniter config passed as a parameter to unmarshal the
// data into the given value(ptr).
func UnmarshalWith(jc jsoniter.API, data []byte, v interface{}) error {
	// See https://github.com/json-iterator/go/blob/master/example_test.go#L69-L88
	iter := jc.BorrowIterator(data)
	defer jc.ReturnIterator(iter)

	iter.ReadVal(v)
	if iter.Error != nil {
		log.WithError(iter.Error).
			Error("Got error while trying to unmarshal value into given struct")
		return errors.Wrap(iter.Error, "util: unmarshal using jsoniter failed")
	}
	return nil
}

// UnmarshalFromString does an unsafe cast from string to byte array to avoid
// the unnecessary allocation and copying and delegates to `Unmarshal`.
func UnmarshalFromString(s string, v interface{}) error { return Unmarshal(strToBytes(s), v) }

// See https://syslog.ravelin.com/byte-vs-string-in-go-d645b67ca7ff

// strToBytes is used when you really want to convert a string
// to a slice of bytes without incurring overhead.
func strToBytes(s string) []byte { return *(*[]byte)(unsafe.Pointer(&s)) }
```

This causes a panic but only in debug mode:
```go
package main

import (
	"genie/util/jsonutil"
)

type MyStruct struct {
	MyField string `json:"myField"`
}

func main() {
	s := `{ "myField": "myValue" }`
	jsonutil.UnmarshalFromString(s, &MyStruct{})
}

```

Stack trace:
```
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
genie/vendor/github.com/json-iterator/go.(*Iterator).ReadString(0xc04208a400, 0x0, 0x0)
	E:/workspace/golang/src/genie/vendor/github.com/json-iterator/go/feature_iter_string.go:15 +0x440
genie/vendor/github.com/json-iterator/go.(*stringCodec).Decode(0x67da50, 0xc042048450, 0xc04208a400)
	E:/workspace/golang/src/genie/vendor/github.com/json-iterator/go/feature_reflect_native.go:15 +0x32
genie/vendor/github.com/json-iterator/go.(*structFieldDecoder).Decode(0xc0420544e0, 0xc042048450, 0xc04208a400)
	E:/workspace/golang/src/genie/vendor/github.com/json-iterator/go/feature_reflect_struct_decoder.go:962 +0x86
genie/vendor/github.com/json-iterator/go.(*oneFieldStructDecoder).Decode(0xc042054540, 0xc042048450, 0xc04208a400)
	E:/workspace/golang/src/genie/vendor/github.com/json-iterator/go/feature_reflect_struct_decoder.go:528 +0xbf
genie/vendor/github.com/json-iterator/go.(*Iterator).ReadVal(0xc04208a400, 0x561100, 0xc042048450)
	E:/workspace/golang/src/genie/vendor/github.com/json-iterator/go/feature_reflect.go:85 +0x110
genie/util/jsonutil.UnmarshalWith(0x5b1640, 0xc04208c180, 0x5a1552, 0x18, 0x0, 0x561100, 0xc042048450, 0x0, 0x0)
	E:/workspace/golang/src/genie/util/jsonutil/unmarshal.go:22 +0xf1
genie/util/jsonutil.Unmarshal(0x5a1552, 0x18, 0x0, 0x561100, 0xc042048450, 0x0, 0x0)
	E:/workspace/golang/src/genie/util/jsonutil/unmarshal.go:13 +0x87
genie/util/jsonutil.UnmarshalFromString(0x5a1552, 0x18, 0x561100, 0xc042048450, 0x0, 0x0)
	E:/workspace/golang/src/genie/util/jsonutil/unmarshal.go:33 +0x96
main.main()
	E:/workspace/golang/src/playground/unmarshal_from_string.go:13 +0xac
```

This might be because of the unsafe manipulation I am doing for the string but I'd be really grateful if you could help and fix it.

**Comment by taowen** [comment]
change `strToBytes(s)` to `[]byte(s)` fixed the problem. or you need to use

```go
func strToBytes(s string) []byte {
	stringHeader := (*reflect.StringHeader)(unsafe.Pointer(&s))
	sliceHeader := &reflect.SliceHeader{
		Data: stringHeader.Data,
		Cap: stringHeader.Len,
		Len: stringHeader.Len,
	}
	return *(*[]byte)(unsafe.Pointer(sliceHeader))
}
```

**Comment by sudo-suhas** [comment]
Thank you so much @taowen!
