### ISSUE TITLE
Marshal Panic

### ISSUE THREAD

**Issue by panshengneng** [json-iterator/go#556]
// ----------------------------------------------------------------------------------------------------------------
// ----------------------------------------------------------------------------------------------------------------
// panic 1
// ----------------------------------------------------------------------------------------------------------------
// ----------------------------------------------------------------------------------------------------------------

goroutine 13829950 [running]:
runtime.throw(0x1cc922f, 0x5)
	/usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc01f9c73c8 sp=0xc01f9c7398 pc=0x434a52
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:702 +0x3cc fp=0xc01f9c73f8 sp=0xc01f9c73c8 pc=0x44babc
github.com/json-iterator/go.(*int32Codec).IsEmpty(0x2ecf180, 0xc029e8a7af5855c5, 0xc03316d758)
	/Users/jenkins/go/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect_native.go:269 +0x5 fp=0xc01f9c7400 sp=0xc01f9c73f8 pc=0x7a82b5
github.com/json-iterator/go.(*placeholderEncoder).IsEmpty(0xc01b47a900, 0xc029e8a7af5855c5, 0x1)
	/Users/jenkins/go/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect.go:336 +0x3d fp=0xc01f9c7428 sp=0xc01f9c7400 pc=0x79bb2d
github.com/json-iterator/go.(*placeholderEncoder).IsEmpty(0xc01b59d9c0, 0xc029e8a7af5855c5, 0xc029e8a7af5855c5)
	/Users/jenkins/go/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect.go:336 +0x3d fp=0xc01f9c7450 sp=0xc01f9c7428 pc=0x79bb2d
github.com/json-iterator/go.(*structFieldEncoder).IsEmpty(0xc01b5a83c0, 0xc029e8a7af5855c5, 0xc03316d701)
	/Users/jenkins/go/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect_struct_encoder.go:118 +0x5e fp=0xc01f9c7478 sp=0xc01f9c7450 pc=0x7b358e
github.com/json-iterator/go.(*structEncoder).Encode(0xc01b5a8480, 0xc029e8a7af5855c5, 0xc03316d740)
	/Users/jenkins/go/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect_struct_encoder.go:148 +0x405 fp=0xc01f9c7530 sp=0xc01f9c7478 pc=0x7b3a85
github.com/json-iterator/go.(*OptionalEncoder).Encode(0xc01b59db10, 0xc03b644b40, 0xc03316d740)
	/Users/jenkins/go/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect_optional.go:74 +0xeb fp=0xc01f9c7580 sp=0xc01f9c7530 pc=0x7a97db
github.com/json-iterator/go.(*placeholderEncoder).Encode(0xc01b59da40, 0xc03b644b40, 0xc03316d740)
	/Users/jenkins/go/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect.go:332 +0x47 fp=0xc01f9c75a8 sp=0xc01f9c7580 pc=0x79bad7
github.com/json-iterator/go.(*sliceEncoder).Encode(0xc01b5b0260, 0xc02df34828, 0xc03316d740)
	/Users/jenkins/go/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect_slice.go:42 +0x153 fp=0xc01f9c7630 sp=0xc01f9c75a8 pc=0x7aa0f3
github.com/json-iterator/go.(*placeholderEncoder).Encode(0xc01b59de70, 0xc02df34828, 0xc03316d740)
	/Users/jenkins/go/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect.go:332 +0x47 fp=0xc01f9c7658 sp=0xc01f9c7630 pc=0x79bad7
github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc01b5d2e40, 0xc02df34700, 0xc03316d740)
	/Users/jenkins/go/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect_struct_encoder.go:110 +0x86 fp=0xc01f9c76e8 sp=0xc01f9c7658 pc=0x7b3376
github.com/json-iterator/go.(*structEncoder).Encode(0xc01b5d3260, 0xc02df34700, 0xc03316d740)
	/Users/jenkins/go/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect_struct_encoder.go:158 +0x3b8 fp=0xc01f9c77a0 sp=0xc01f9c76e8 pc=0x7b3a38
github.com/json-iterator/go.(*OptionalEncoder).Encode(0xc01b5c7630, 0xc03cdafe30, 0xc03316d740)
	/Users/jenkins/go/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect_optional.go:74 +0xeb fp=0xc01f9c77f0 sp=0xc01f9c77a0 pc=0x7a97db
github.com/json-iterator/go.(*sliceEncoder).Encode(0xc01b5d6900, 0xc02df34468, 0xc03316d740)
	/Users/jenkins/go/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect_slice.go:38 +0xef fp=0xc01f9c7878 sp=0xc01f9c77f0 pc=0x7aa08f
github.com/json-iterator/go.(*placeholderEncoder).Encode(0xc01b5c62f0, 0xc02df34468, 0xc03316d740)
	/Users/jenkins/go/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect.go:332 +0x47 fp=0xc01f9c78a0 sp=0xc01f9c7878 pc=0x79bad7
github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc01b5df110, 0xc02df34380, 0xc03316d740)
	/Users/jenkins/go/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect_struct_encoder.go:110 +0x86 fp=0xc01f9c7930 sp=0xc01f9c78a0 pc=0x7b3376
github.com/json-iterator/go.(*structEncoder).Encode(0xc01b5df410, 0xc02df34380, 0xc03316d740)
	/Users/jenkins/go/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect_struct_encoder.go:158 +0x3b8 fp=0xc01f9c79e8 sp=0xc01f9c7930 pc=0x7b3a38
github.com/json-iterator/go.(*OptionalEncoder).Encode(0xc01b5e0700, 0xc02df3a5a8, 0xc03316d740)
	/Users/jenkins/go/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect_optional.go:74 +0xeb fp=0xc01f9c7a38 sp=0xc01f9c79e8 pc=0x7a97db
github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc01b5e67e0, 0xc02df3a580, 0xc03316d740)
	/Users/jenkins/go/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect_struct_encoder.go:110 +0x86 fp=0xc01f9c7ac8 sp=0xc01f9c7a38 pc=0x7b3376
github.com/json-iterator/go.(*structEncoder).Encode(0xc01b5e6c00, 0xc02df3a580, 0xc03316d740)
	/Users/jenkins/go/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect_struct_encoder.go:158 +0x3b8 fp=0xc01f9c7b80 sp=0xc01f9c7ac8 pc=0x7b3a38
github.com/json-iterator/go.(*OptionalEncoder).Encode(0xc01b5e1410, 0xc037e20500, 0xc03316d740)
	/Users/jenkins/go/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect_optional.go:74 +0xeb fp=0xc01f9c7bd0 sp=0xc01f9c7b80 pc=0x7a97db
github.com/json-iterator/go.(*onePtrEncoder).Encode(0xc01b5e1420, 0xc02df3a580, 0xc03316d740)
	/Users/jenkins/go/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect.go:219 +0x68 fp=0xc01f9c7bf8 sp=0xc01f9c7bd0 pc=0x79ade8
github.com/json-iterator/go.(*Stream).WriteVal(0xc03316d740, 0x1c9cde0, 0xc02df3a580)
	/Users/jenkins/go/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect.go:98 +0x146 fp=0xc01f9c7c60 sp=0xc01f9c7bf8 pc=0x799c86
github.com/json-iterator/go.(*frozenConfig).Marshal(0xc00013cbe0, 0x1c9cde0, 0xc02df3a580, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/jenkins/go/pkg/mod/github.com/json-iterator/go@v1.1.9/config.go:299 +0xaf fp=0xc01f9c7cd0 sp=0xc01f9c7c60 pc=0x78f46f
github.com/json-iterator/go.Marshal(...)
	/Users/jenkins/go/pkg/mod/github.com/json-iterator/go@v1.1.9/adapter.go:34
game/model.(*Room).Save(0xc02df3a580)
	/Users/jenkins/game/model/room.go:146 +0x105 fp=0xc01f9c7ee8 sp=0xc01f9c7cd0 pc=0x16c3f25

// ----------------------------------------------------------------------------------------------------------------
// ----------------------------------------------------------------------------------------------------------------
// panic 2
// ----------------------------------------------------------------------------------------------------------------
// ----------------------------------------------------------------------------------------------------------------

goroutine 1355841 [running]:
runtime.throw(0x1cc922f, 0x5)
	/usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc01a291290 sp=0xc01a291260 pc=0x434a52
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:702 +0x3cc fp=0xc01a2912c0 sp=0xc01a291290 pc=0x44babc
github.com/json-iterator/go.(*OptionalEncoder).Encode(0xc01c0ad150, 0x206e692074726f70, 0xc038ff6060)
	/Users/jenkins/go/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect_optional.go:71 +0x26 fp=0xc01a291310 sp=0xc01a2912c0 pc=0x7a9716
github.com/json-iterator/go.(*placeholderEncoder).Encode(0xc01c0ad020, 0x206e692074726f70, 0xc038ff6060)
	/Users/jenkins/go/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect.go:332 +0x47 fp=0xc01a291338 sp=0xc01a291310 pc=0x79bad7
github.com/json-iterator/go.(*sliceEncoder).Encode(0xc01c0a93e0, 0x1ce3c4a, 0xc038ff6060)
	/Users/jenkins/go/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect_slice.go:38 +0xef fp=0xc01a2913c0 sp=0xc01a291338 pc=0x7aa08f
github.com/json-iterator/go.(*placeholderEncoder).Encode(0xc01c0ad1c0, 0x1ce3c4a, 0xc038ff6060)
	/Users/jenkins/go/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect.go:332 +0x47 fp=0xc01a2913e8 sp=0xc01a2913c0 pc=0x79bad7
github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc01c0b8030, 0x1ce3c42, 0xc038ff6060)
	/Users/jenkins/go/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect_struct_encoder.go:110 +0x86 fp=0xc01a291478 sp=0xc01a2913e8 pc=0x7b3376
github.com/json-iterator/go.(*structEncoder).Encode(0xc01c0b80c0, 0x1ce3c42, 0xc038ff6060)
	/Users/jenkins/go/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect_struct_encoder.go:158 +0x3b8 fp=0xc01a291530 sp=0xc01a291478 pc=0x7b3a38
github.com/json-iterator/go.(*OptionalEncoder).Encode(0xc01c0ad7a0, 0xc036acc120, 0xc038ff6060)
	/Users/jenkins/go/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect_optional.go:74 +0xeb fp=0xc01a291580 sp=0xc01a291530 pc=0x7a97db
github.com/json-iterator/go.(*placeholderEncoder).Encode(0xc01c0ad6d0, 0xc036acc120, 0xc038ff6060)
	/Users/jenkins/go/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect.go:332 +0x47 fp=0xc01a2915a8 sp=0xc01a291580 pc=0x79bad7
github.com/json-iterator/go.(*sliceEncoder).Encode(0xc01c0a9d60, 0xc0377dd0e8, 0xc038ff6060)
	/Users/jenkins/go/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect_slice.go:42 +0x153 fp=0xc01a291630 sp=0xc01a2915a8 pc=0x7aa0f3
github.com/json-iterator/go.(*placeholderEncoder).Encode(0xc01c0adb00, 0xc0377dd0e8, 0xc038ff6060)
	/Users/jenkins/go/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect.go:332 +0x47 fp=0xc01a291658 sp=0xc01a291630 pc=0x79bad7
github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc01c0daa80, 0xc0377dcfc0, 0xc038ff6060)
	/Users/jenkins/go/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect_struct_encoder.go:110 +0x86 fp=0xc01a2916e8 sp=0xc01a291658 pc=0x7b3376
github.com/json-iterator/go.(*structEncoder).Encode(0xc01c0daea0, 0xc0377dcfc0, 0xc038ff6060)
	/Users/jenkins/go/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect_struct_encoder.go:158 +0x3b8 fp=0xc01a2917a0 sp=0xc01a2916e8 pc=0x7b3a38
github.com/json-iterator/go.(*OptionalEncoder).Encode(0xc01c0d32c0, 0xc032c8db70, 0xc038ff6060)
	/Users/jenkins/go/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect_optional.go:74 +0xeb fp=0xc01a2917f0 sp=0xc01a2917a0 pc=0x7a97db
github.com/json-iterator/go.(*sliceEncoder).Encode(0xc01c0de400, 0xc0377dcd28, 0xc038ff6060)
	/Users/jenkins/go/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect_slice.go:38 +0xef fp=0xc01a291878 sp=0xc01a2917f0 pc=0x7aa08f
github.com/json-iterator/go.(*placeholderEncoder).Encode(0xc01c0bdf80, 0xc0377dcd28, 0xc038ff6060)
	/Users/jenkins/go/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect.go:332 +0x47 fp=0xc01a2918a0 sp=0xc01a291878 pc=0x79bad7
github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc01c0ead50, 0xc0377dcc40, 0xc038ff6060)
	/Users/jenkins/go/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect_struct_encoder.go:110 +0x86 fp=0xc01a291930 sp=0xc01a2918a0 pc=0x7b3376
github.com/json-iterator/go.(*structEncoder).Encode(0xc01c0eb050, 0xc0377dcc40, 0xc038ff6060)
	/Users/jenkins/go/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect_struct_encoder.go:158 +0x3b8 fp=0xc01a2919e8 sp=0xc01a291930 pc=0x7b3a38
github.com/json-iterator/go.(*OptionalEncoder).Encode(0xc01c0ee390, 0xc0379ca708, 0xc038ff6060)
	/Users/jenkins/go/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect_optional.go:74 +0xeb fp=0xc01a291a38 sp=0xc01a2919e8 pc=0x7a97db
github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc01c0f2420, 0xc0379ca6e0, 0xc038ff6060)
	/Users/jenkins/go/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect_struct_encoder.go:110 +0x86 fp=0xc01a291ac8 sp=0xc01a291a38 pc=0x7b3376
github.com/json-iterator/go.(*structEncoder).Encode(0xc01c0f2840, 0xc0379ca6e0, 0xc038ff6060)
	/Users/jenkins/go/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect_struct_encoder.go:158 +0x3b8 fp=0xc01a291b80 sp=0xc01a291ac8 pc=0x7b3a38
github.com/json-iterator/go.(*OptionalEncoder).Encode(0xc01c0ef0b0, 0xc0213c2ad0, 0xc038ff6060)
	/Users/jenkins/go/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect_optional.go:74 +0xeb fp=0xc01a291bd0 sp=0xc01a291b80 pc=0x7a97db
github.com/json-iterator/go.(*onePtrEncoder).Encode(0xc01c0ef0c0, 0xc0379ca6e0, 0xc038ff6060)
	/Users/jenkins/go/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect.go:219 +0x68 fp=0xc01a291bf8 sp=0xc01a291bd0 pc=0x79ade8
github.com/json-iterator/go.(*Stream).WriteVal(0xc038ff6060, 0x1c9cde0, 0xc0379ca6e0)
	/Users/jenkins/go/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect.go:98 +0x146 fp=0xc01a291c60 sp=0xc01a291bf8 pc=0x799c86
github.com/json-iterator/go.(*frozenConfig).Marshal(0xc00011cb40, 0x1c9cde0, 0xc0379ca6e0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/jenkins/go/pkg/mod/github.com/json-iterator/go@v1.1.9/config.go:299 +0xaf fp=0xc01a291cd0 sp=0xc01a291c60 pc=0x78f46f
github.com/json-iterator/go.Marshal(...)
	/Users/jenkins/go/pkg/mod/github.com/json-iterator/go@v1.1.9/adapter.go:34
game/model.(*Room).Save(0xc0379ca6e0)
	/Users/jenkins/game/model/room.go:146 +0x105 fp=0xc01a291ee8 sp=0xc01a291cd0 pc=0x16c3f25

**Comment by cupen** [comment]
how to reproduce it?
