### ISSUE TITLE
panic

### ISSUE THREAD

**Issue by li-bit** [json-iterator/go#593]
unexpected fault address 0x186a0
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x186a0 pc=0x81497b]

goroutine 2640123 [running]:
runtime.throw(0x17cb2c8, 0x5)
        /usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0xc0068e8148 sp=0xc0068e8118 pc=0x438432
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:741 +0x268 fp=0xc0068e8180 sp=0xc0068e8148 pc=0x44fb88
github.com/json-iterator/go.(*Stream).WriteStringWithHTMLEscaped(0xc01e127200, 0x186a0, 0x43bfecb8f9718)
        /usr1/go/pkg/mod/github.com/json-iterator/go@v1.1.11/stream_str.go:227 +0x7b fp=0xc0068e81e8 sp=0xc0068e8180 pc=0x81497b
github.com/json-iterator/go.(*htmlEscapedStringEncoder).Encode(0x2d009c8, 0x2d009e8, 0xc01e127200)
        /usr1/go/pkg/mod/github.com/json-iterator/go@v1.1.11/config.go:263 +0x45 fp=0xc0068e8210 sp=0xc0068e81e8 pc=0x7e6f65
github.com/json-iterator/go.(*sliceEncoder).Encode(0xc00000c618, 0xc00be35ad0, 0xc01e127200)
        /usr1/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_slice.go:42 +0x2f6 fp=0xc0068e82c8 sp=0xc0068e8210 pc=0x803f36
github.com/json-iterator/go.(*placeholderEncoder).Encode(0xc001b3ef80, 0xc00be35ad0, 0xc01e127200)
        /usr1/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect.go:332 +0x47 fp=0xc0068e82f0 sp=0xc0068e82c8 pc=0x7f4067
github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc001dbd500, 0xc00be35a40, 0xc01e127200)
        /usr1/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_struct_encoder.go:110 +0x78 fp=0xc0068e8378 sp=0xc0068e82f0 pc=0x80d618
github.com/json-iterator/go.(*structEncoder).Encode(0xc001dbd620, 0xc00be35a40, 0xc01e127200)
        /usr1/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_struct_encoder.go:158 +0x677 fp=0xc0068e8458 sp=0xc0068e8378 pc=0x80dfb7
github.com/json-iterator/go.(*sliceEncoder).Encode(0xc00000d0b0, 0xc00c932ea8, 0xc01e127200)
        /usr1/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_slice.go:42 +0x2f6 fp=0xc0068e8510 sp=0xc0068e8458 pc=0x803f36
github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc001dbd920, 0xc00c932c80, 0xc01e127200)
        /usr1/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_struct_encoder.go:110 +0x78 fp=0xc0068e8598 sp=0xc0068e8510 pc=0x80d618
github.com/json-iterator/go.(*structEncoder).Encode(0xc001dbd9b0, 0xc00c932c80, 0xc01e127200)
        /usr1/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_struct_encoder.go:158 +0x677 fp=0xc0068e8678 sp=0xc0068e8598 pc=0x80dfb7
github.com/json-iterator/go.(*Stream).WriteVal(0xc01e127200, 0x1779e40, 0xc00c932c80)
        /usr1/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect.go:98 +0x150 fp=0xc0068e86e0 sp=0xc0068e8678 pc=0x7f2130
github.com/json-iterator/go.(*dynamicEncoder).Encode(0xc001a32b90, 0xc01e311848, 0xc01e127200)
        /usr1/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_dynamic.go:15 +0x65 fp=0xc0068e8710 sp=0xc0068e86e0 pc=0x7f5365
github.com/json-iterator/go.(*sortKeysMapEncoder).Encode(0xc0003781b0, 0xc00cc51378, 0xc026b08cc0)
        /usr1/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_map.go:311 +0x4a8 fp=0xc0068e8880 sp=0xc0068e8710 pc=0x7fcee8
github.com/json-iterator/go.(*onePtrEncoder).Encode(0xc001a32ba0, 0xc001dbcc30, 0xc026b08cc0)
        /usr1/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect.go:219 +0x68 fp=0xc0068e88a8 sp=0xc0068e8880 pc=0x7f32e8
github.com/json-iterator/go.(*Stream).WriteVal(0xc026b08cc0, 0x161e380, 0xc001dbcc30)
        /usr1/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect.go:98 +0x150 fp=0xc0068e8910 sp=0xc0068e88a8 pc=0x7f2130
github.com/json-iterator/go.(*frozenConfig).Marshal(0xc0000dfc20, 0x161e380, 0xc001dbcc30, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr1/go/pkg/mod/github.com/json-iterator/go@v1.1.11/config.go:299 +0xaf fp=0xc0068e8980 sp=0xc0068e8910 pc=0x7e72ef
github.com/json-iterator/go.API.Marshal-fm(0x161e380, 0xc001dbcc30, 0x2caa510, 0x1, 0x1, 0x120, 0x7f4acdddd418)
        /usr1/go/pkg/mod/github.com/json-iterator/go@v1.1.11/config.go:36 +0x4c fp=0xc0068e89d0 sp=0xc0068e8980 pc=0x81b9cc
github.com/gin-gonic/gin/render.WriteJSON(0x7f4bd10eda38, 0xc006104700, 0x161e380, 0xc001dbcc30, 0xc00038c000, 0x7f4bd10eda38)
        /usr1/go/pkg/mod/github.com/gin-gonic/gin@v1.7.3/render/json.go:69 +0x7c fp=0xc0068e8a18 sp=0xc0068e89d0 pc=0x1015d5c
github.com/gin-gonic/gin/render.JSON.Render(...)
        /usr1/go/pkg/mod/github.com/gin-gonic/gin@v1.7.3/render/json.go:55
github.com/gin-gonic/gin/render.(*JSON).Render(0xc04d1e91e0, 0x7f4bd10eda38, 0xc006104700, 0x7f4bd10eda38, 0xc006104700)
        <autogenerated>:1 +0x65 fp=0xc0068e8a58 sp=0xc0068e8a18 pc=0x1018965
github.com/gin-gonic/gin.(*Context).Render(0xc006104700, 0xc8, 0x1ae8ee0, 0xc04d1e91e0)
        /usr1/go/pkg/mod/github.com/gin-gonic/gin@v1.7.3/context.go:913 +0x149 fp=0xc0068e8a98 sp=0xc0068e8a58 pc=0x101e569
github.com/gin-gonic/gin.(*Context).JSON(...)
        /usr1/go/pkg/mod/github.com/gin-gonic/gin@v1.7.3/context.go:956
pipeline-x/ctrl/router/api/v1.getRelationGraph(0xc006104700)
        /usr1/home/workspace/x/w/4842cdaab98dc25c/exec.d/ctrl/router/api/v1/build.go:64 +0x3e8 fp=0xc0068e9490 sp=0xc0068e8a98 pc=0x1480948
github.com/gin-gonic/gin.(*Context).Next(...)
        /usr1/go/pkg/mod/github.com/gin-gonic/gin@v1.7.3/context.go:165
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1(0xc006104700)
        /usr1/go/pkg/mod/github.com/gin-gonic/gin@v1.7.3/recovery.go:99 +0x7a fp=0xc0068e94e0 sp=0xc0068e9490 pc=0x102f51a
github.com/gin-gonic/gin.(*Context).Next(...)
        /usr1/go/pkg/mod/github.com/gin-gonic/gin@v1.7.3/context.go:165
pipeline-x/router.record.func1(0xc006104700)

**Comment by 1fge** [comment]
If anyone else runs into this issue in the future, try to update the go-modern/reflect2 package.
