### ISSUE TITLE
Unmarshal structs with fields that have UnmarshalJSON doesn't work

### ISSUE THREAD

**Issue by thockin** [json-iterator/go#76]
```
package main

import (
    "bytes"
    "encoding/json"                                                                                                            
    "fmt"
    "strings"

    "github.com/davecgh/go-spew/spew"
    jsoniter "github.com/json-iterator/go"
)

type Marshaler struct {
    X string
}

func (m Marshaler) MarshalJSON() ([]byte, error) {
    return []byte(`"MANUAL__` + m.X + `"`), nil 
}

func (m *Marshaler) UnmarshalJSON(text []byte) error {
    m.X = strings.TrimPrefix(strings.Trim(string(text), `"`), "MANUAL__")
    return nil 
}

var _ json.Marshaler = Marshaler{}
var _ json.Unmarshaler = &Marshaler{}

type T struct {
    M Marshaler
}

func main() {
    var before T

    jbStd, err := json.Marshal(before)
    if err != nil {
        panic(fmt.Sprintf("failed to marshal with stdlib: %v", err))
    }
    jbIter, err := jsoniter.ConfigCompatibleWithStandardLibrary.Marshal(before)
    if err != nil {
        panic(fmt.Sprintf("failed to marshal with jsoniter: %v", err))
    }
    if string(jbStd) != string(jbIter) {
        panic(fmt.Sprintf("marshal expected:\n    %s\ngot:\n    %s\nobj:\n    %s",
            indent(jbStd, "    "), indent(jbIter, "    "), dump(before)))
    }                                                                                                                          

    var afterStd T
    err = json.Unmarshal(jbIter, &afterStd)
    if err != nil {
        panic(fmt.Sprintf("failed to unmarshal with stdlib: %v\nvia:\n    %s",
            err, indent(jbIter, "    ")))
    }
    var afterIter T
    err = jsoniter.ConfigCompatibleWithStandardLibrary.Unmarshal(jbIter, &afterIter)
    if err != nil {
        panic(fmt.Sprintf("failed to unmarshal with jsoniter: %v\nvia:\n    %s",
            err, indent(jbIter, "    ")))
    }
    if fingerprint(afterStd) != fingerprint(afterIter) {
        panic(fmt.Sprintf("unmarshal expected:\n    %s\ngot:\n    %s\nvia:\n    %s",
            dump(afterStd), dump(afterIter), indent(jbIter, "    ")))
    }
}

const indentStr = ">  "

func fingerprint(obj interface{}) string {
    c := spew.ConfigState{
        SortKeys: true,
        SpewKeys: true,
    }
    return c.Sprintf("%v", obj)
}

func dump(obj interface{}) string {
    cfg := spew.ConfigState{
        Indent: indentStr,
    }
    return cfg.Sdump(obj)
}

func indent(src []byte, prefix string) string {
    var buf bytes.Buffer
    err := json.Indent(&buf, src, prefix, indentStr)
    if err != nil {
        return fmt.Sprintf("!!! %v", err)
    }
    return buf.String()
}                                          
```

When run:

```
panic: failed to unmarshal with jsoniter: main.T: M: readObjectStart: expect { or n, parsing 6 ...{"M":"... at {"M":"MANUAL__"}
via:
    {
    >  "M": "MANUAL__"
    }

goroutine 1 [running]:
main.main()
	/tmp/js.go:59 +0x937
exit status 2
```

**Comment by thockin** [comment]
Same for TextUnmarshal.

**Comment by thockin** [comment]
Same for map keys with TextUnmarshal

**Comment by taowen** [comment]
output_tests/map_key_text_marshal/struct_alias

json_test.go:23: failed to marshal with stdlib: json: unsupported type: test.T

seems like the standard library can not json marshal TextMarshaler

**Comment by thockin** [comment]
Will send PR
