### ISSUE TITLE
embedded fields with tag name="" are wrong (and sometimes panic)

### ISSUE THREAD

**Issue by thockin** [json-iterator/go#91]
This one is a bit complex, but came up in kubernetes:

```
package test

type O1 struct {
	O1F string
}

type Option struct {
	O1 *O1
}

type T struct {
	Option `json:","`
}
```

produces EITHER:

```
--- FAIL: Test_Roundtrip (0.00s)
	json_test.go:37: marshal expected:
		    {
		    >  "O1": {
		    >  >  "O1F": "À嶼åz垹nǽ揫Sl駾ǟ"
		    >  }
		    }
		got:
		    {
		    >  "Option": {
		    >  >  "O1": {
		    >  >  >  "O1F": ""
		    >  >  }
		    >  }
		    }
		obj:
		    (test.T) {
		>  Option: (test.Option) {
		>  >  O1: (*test.O1)(0xc42000f190)({
		>  >  >  O1F: (string) (len=24) "À嶼åz垹nǽ揫Sl駾ǟ"
		>  >  })
		>  }
		}
```

OR:

```
--- FAIL: Test_Roundtrip (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x581212]

goroutine 5 [running]:
testing.tRunner.func1(0xc42006e750)
	/usr/local/go/src/testing/testing.go:622 +0x29d
panic(0x5de060, 0x70fa10)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/json-iterator/go.(*optionalEncoder).Encode(0xc42000f470, 0x0, 0xc420014910)
	/home/thockin/src/go/src/github.com/json-iterator/go/feature_reflect.go:117 +0x22
github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc42000b360, 0x0, 0xc420014910)
	/home/thockin/src/go/src/github.com/json-iterator/go/feature_reflect_object.go:1033 +0x5c
github.com/json-iterator/go.(*structEncoder).Encode(0xc42000b3c0, 0x0, 0xc420014910)
	/home/thockin/src/go/src/github.com/json-iterator/go/feature_reflect_object.go:1070 +0xc2
github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc42000b420, 0x0, 0xc420014910)
	/home/thockin/src/go/src/github.com/json-iterator/go/feature_reflect_object.go:1033 +0x5c
github.com/json-iterator/go.(*structEncoder).Encode(0xc42000b480, 0x0, 0xc420014910)
	/home/thockin/src/go/src/github.com/json-iterator/go/feature_reflect_object.go:1070 +0xc2
github.com/json-iterator/go.(*structEncoder).EncodeInterface(0xc42000b480, 0x5e3680, 0x0, 0xc420014910)
	/home/thockin/src/go/src/github.com/json-iterator/go/feature_reflect_object.go:1090 +0xe9
github.com/json-iterator/go.(*Stream).WriteVal(0xc420014910, 0x5e3680, 0x0)
	/home/thockin/src/go/src/github.com/json-iterator/go/feature_reflect.go:230 +0xe4
github.com/json-iterator/go.(*frozenConfig).Marshal(0xc42006ccc0, 0x5e3680, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/thockin/src/go/src/github.com/json-iterator/go/feature_config.go:219 +0xdb
github.com/json-iterator/go/output_tests/xxx.Test_Roundtrip(0xc42006e750)
	/home/thockin/src/go/src/github.com/json-iterator/go/output_tests/xxx/json_test.go:28 +0x20a
testing.tRunner(0xc42006e750, 0x61e998)
	/usr/local/go/src/testing/testing.go:657 +0x96
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:697 +0x2ca
FAIL	github.com/json-iterator/go/output_tests/xxx	0.034s
```

**Comment by taowen** [comment]
fixed
